
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int print = 15;
  public static final int tint = 8;
  public static final int llac = 3;
  public static final int cadena = 11;
  public static final int llaa = 2;
  public static final int repetir = 16;
  public static final int tstring = 10;
  public static final int EOF = 0;
  public static final int entero = 12;
  public static final int puntoycoma = 7;
  public static final int doble = 13;
  public static final int error = 1;
  public static final int tdouble = 9;
  public static final int parc = 5;
  public static final int identificador = 14;
  public static final int igual = 6;
  public static final int para = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "llaa",
  "llac",
  "para",
  "parc",
  "igual",
  "puntoycoma",
  "tint",
  "tdouble",
  "tstring",
  "cadena",
  "entero",
  "doble",
  "identificador",
  "print",
  "repetir"
  };
}

